LXD-OlBcPK4:
  H3TD: ${4Vj_JAKo:9C1KcBjnn}
  stvf: ${KTx_DKnF:xE49}
  iNtk743-92w41SAt: ${9UlwOrg_outf2I8p:/nKSFt}
  HmhDlk:
    dJYuM48k: ${ymUaad_Rrm1fw2y:0pYx}
    K5sR: ${zBsnda_EogJ:BOJrcXfjS}
    2ueQ: ${5YhwLz_08ZR:yhmh}
    vGm7:
      xWSjWLHm: ${y11Yaw_eUhw_ZY8fYcz0:/Aegf}
    N0gP-Kulj:
      p4yX8TRg: ${pn7kNx_STHy_4ryp_yJOAZ85L:/bC0a/59PE}
      5AuUOs-0owHqYJt: ${g2qjG0_o8vX_yFXq_ZlxJ6v_rwxkr4qI:eR2Nso}
  YuRm-5kZyXx:
    Wu-Ye11f8: ${8I9E_WpD0MM_lj_eV9QLL:OTr9}
    xjO-x5nn-aLpN: ${ZRWP_EHu5KR_T73_rQHp_J6Xr:2LWl4u7u}  # iB IA
  HaO9bu3M4a:
    zAeeCpJ-Cuy-jxm-57zhHq: ${7bgeqD1E52_FMaAU4a_BNs_HA9_DNBka6:JtFP}
  ECIAB:
    iye-OPllHtZ-dpSc: ${cJ6LL_QZP_CkOHd1L_HGyH:Gj6jf4E1}  # UA YV (tbbp-ENM-98NM)  +  C Sy QAX ORp8E2l tUtkhqVJ  [rcwOxEZP gBdX]
    XdO5f-X4G-CAWWV: ${rlyRh_cjliV_jRy_W3NEK:rWIvpjbV}  # EM Qx (iNzY-XBd-60dj)  +  N qY qKj b6TWEET 6BSzrc6q  [uxhwzXbC 7P0f]
  5Pjf1xB9:
    otyNTzlY:
      bbzg-m5cAuKsSD: ${Hl_GwjDMJsH_sVRI_cwnnC6PXj:PAOo}

yQbqLZ:
  8BrYMSWWfAi:
    aOOe: ${6ux_6lVu:jgJaQx}
  44SsUtQtJ:
    ZReCE9m: PwQtq
  x4oSGlY:
    OxUND6LYs:
      jjo-9oBU-19bp: ${8JF-sJ1J9GF.SLF5-1iB6Cd.YNC-UpI4-MpE8}
  W9QiOi:
    ehRh:
      Kx8iUDb:
        h0i5QxCb: "*"
  Rhpb9WHuF0:
    asO: WTKS:CRysqdmjc9://${Kr_WZfX:m6P3msHlb}:${o0_D7Cn:aGhT}/${nv_vK36yQTS:kxcw6P_ufELv07RR}
    3g5Zc6W9: ${VF_yqqx4vLh:9hW1YWz}
    cffB0yzW: ${et_KlBX4uLZ:RQPm1cdIG}
    W6uBgy-HSv4n-wJmu: C7l.ZoJzeq6lOh.kOE3Rj
  DWV:
    UAj5wieAW:
      8n5-q0PR: Xnki02E0
    flO9KovM-03K9Wdrb: 2Ep.uaHIRbNud.aQVIvGL.fkBV0EcUmf4VtyXhO
    Ylz1b5MEXT:
      OvCRGs2oV:
        Lr6jXVi: ToS.S8rqMcH1c.ylTTFdM.9EAPdN5ijbfzRCLw8
        kXAaQj_9PT: JA8P
    3ZY4-7c0: XVb94

qnr6K6pMm:
  WfTLTWA-S1:
    mydz: /H29Z7HL5W

i18arp:
  kWRs: ${79x-WiE7hx1.PZet}

CwKncb:
  DUvlO9WX:
    ku5t9VqAY: EzxJ
  Ya6-wUH6Q6l: /*
  bziVqjKOAs0: "/abCH8rq-F5/**, /f0/nZU-iVYT/**, ${KwSPqeKti.Q6Mqx3m-jr.ZicK}, /JnxFnl-LZwh/**"
